data:
  root: "./datasets/GOPRO"
  train_dir: "train"
  test_dir: "test"
  input_dir: "blur"
  target_dir: "sharp"  
  image_size: 256
  max_len: 1  

model:
  in_chans: 3
  out_chans: 3
  base_chans: 40
  scales: 4
  factor_r: 16
  d: 64
  d_v: 64
loss:
    charbonnier: 1.0  
    perceptual: 0.2  
    # ssim: 0.1
    # grad: 0.2         

training:
  model_dir: "./outputs_GOPRO"
  learning_rate: 0.0001
  weight_decay: 2e-5
  warmup_epochs: 0
  print_freq: 100
  
  optimization:
    optimizer:
      name: "AdamW"
      lr: 0.0001
      weight_decay: 0.0001
      betas: [0.9, 0.999]
    
    scheduler:
      name: "CosineAnnealingLR"
      T_max: 200
      eta_min: 0.00001

evaluation:
  metrics: ["psnr", "ssim", "lpips"]
  save_images: true
  save_high_res: false 